#!/usr/bin/env bash

restart_waybar() {
    #restart the waybar
    pkill waybar

    waybar --log-level error --config "$HOME/.config/waybar/config" --style "$HOME/.config/waybar/style.css"
}

if [[ "$1" == "--rwb" ]]; then
    restart_waybar
fi
